version: "3.4"
services:
  objetivos:
    container_name: objetivos
    image: nginx
    restart: unless-stopped
    networks:
      - t2_proxy
    volumes:
      - $PWD:/usr/share/nginx/html # config files
    ports:
      - 84:80
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.obj-rtr.entrypoints=https"
      - "traefik.http.routers.obj-rtr.rule=Host(`objetivos.matirivas.me`)"
      - "traefik.http.routers.obj-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.obj-rtr.middlewares=chain-no-auth@file" # No Authentication
#     - "traefik.http.routers.radarr-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      #- "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.obj-rtr.service=obj-svc"
      - "traefik.http.services.obj-svc.loadbalancer.server.port=80"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge
